# -*- coding: utf-8 -*-
"""Tugas 3 Dasprog Rayhan Lutfi Hakim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AilIaRSHk89w3k7dXakHPI9hDEKJn6eP
"""

# MS
jml_sepatu = int(input("Masukkan jumlah sepatu: "))
kanan = []
kiri = []

for i in range(jml_sepatu):
    kode_anomali = input('').strip()

    sisi = ''
    for bagian in kode_anomali:
        if bagian.isupper():#untuk bagian sepatu kiri atau kanan
            sisi = bagian

    kode_angka = []
    for angka in kode_anomali: #untuk ukuran sepatu
        if angka.isdigit():
            kode_angka.append(angka)

    ukuran = ''.join(kode_angka)

    if sisi == 'L':
        kiri.append(ukuran)
    else:
        kanan.append(ukuran)

berpasangan = 0
for sepasang in kiri[:]: #agar saat angka yang ditentukan dihapus, akan tetap terprint
    if sepasang in kanan:
        berpasangan += 1
        kanan.remove(sepasang) #menghapus ukuran sepatu yang sudah berpasangan agar tidak dihitung lagi
        kiri.remove(sepasang)
print(berpasangan)

# Djumanto kebingungan
N = int(input())
kalimat = []
for _ in range(N):
  kode = int(input())
  biner = bin(kode)[2:] #0bbiner agar 0b dihilangkan
  angka = biner.zfill(32)
  string = str(angka)
  for kata in range(0, len(string), 8):
    huruf = string[kata:kata + 8]
    bit = int(huruf, 2)
    kalimat.append(bit)

print(''.join(chr(huruf) for huruf in kalimat))

# TP1
Days = int(input())
hasil_semua = []
for i in range(Days):
    SN = int(input())
    M = input()
    hasil = ''

    for huruf in M:
        if huruf.isalpha():
            if huruf.islower():
                huruf_baru = (ord(huruf) - ord('a') + SN) % 26 + ord('a')
                hasil += chr(huruf_baru)
        elif huruf == " ":
            hasil += huruf

    hasil_semua.append(hasil)

for i in hasil_semua:
    print(i)

# SEBANGKU
N, r, c = map(int, input().split())

kursi = []
for _ in range(N):
    baris = list(map(int, input().split()))
    kursi.append(baris)

for i in range(len(kursi)):
    id = kursi[i][0]
    sebelahan = []
    for j in range(len(kursi)):
        if i != j:
            if kursi[i][1] == kursi[j][1] and abs(kursi[i][2] - kursi[j][2]) == 1:
                sebelahan.append(kursi[j][0])
    # [1, 1, 1],
    # [2, 1, 2],
    # [3, 3, 3],
    # [4, 2, 1],
    # [5, 3, 2]
    if sebelahan:
        for orang in sebelahan:
            print(f"{id}: {orang}")
    else:
        print(f"{id}: 0")

# IUP 1
N = int(input("Masukkan banyaknya perintah: "))
kalimat = input("Masukkan kalimat: ")
for i in range(N):
    kalimat = kalimat[1:] + kalimat[0]
print(kalimat)

# Tangga segitiga
panjang = int(input())
ganjil = ['IU']
genap = ['UI']
for i in range(1, panjang + 1):
  for j in range(1 , i + 1):
    if j % 2 == 0:
     pola =''.join((genap[:i]))
     print(pola)
    else:
      pola = ''.join((ganjil[:i]))
      print(pola)

# IUP 5
jml_barang = int(input("Masukkan jumlah barang: "))
stok = []

for i in range(jml_barang):
    barang = input("Barang dan Jumlah barang: ").split()
    nama_barang = barang[0]
    jumlah_barang = int(barang[1])
    stok.append([nama_barang, jumlah_barang])

beli = int(input("Masukkan jumlah pembelian: "))
for _ in range(beli):
    beli_barang = input("Barang dan Jumlah barang yang dibeli: ").split()
    nama_beli = beli_barang[0]
    jumlah_beli = int(beli_barang[1])

    for j in range(len(stok)):
        if stok[j][0] == nama_beli:
            stok[j][1] -= jumlah_beli

for item in stok:
    print(f'{item[0]}:{item[1]}')

# FTG